[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.dprint]
command = "dprint"
options = ["fmt"]
includes = ["*.json", "*.toml", "*.md"]

[formatter.satysfi-fmt]
command = "satysfi-fmt-each"
includes = ["*.saty", "*.satyh"]
