name: CI

on:
  push:

jobs:
  treefmt:
    name: treefmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
         name: sno2wman
         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix-shell --run "treefmt --fail-on-change"

  flake-check:
    name: flake-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - uses: cachix/cachix-action@v10
        with:
         name: sno2wman
         authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check
